- name: install openssh package
  yum: name=openssh

- name: include credentials info
  include_vars: "{{ credentials_file }}"
  when: credentials_file is defined

- name: create key directory
  file: path={{ item.path | dirname }} mode=0755 state=directory
  with_items: ssh_key_files

- name: create key pair
  shell: ssh-keygen -N "{{ item.password }}" -f {{ item.path }} creates={{ item.path }}
  with_items: ssh_key_files
