- name: install openssh package
  yum: name=openssh

- name: include credentials info
  include_vars: "{{ credentials_file }}"
  when: credentials_file is defined

- name: create key directory
  file: path={{ item.path | dirname }} mode=0755 state=directory
  with_items: ssh_key_files

- name: check if the key exists
  stat: path={{ item.path }}
  register: result
  with_items: ssh_key_files

- name: create key pair
  shell: ssh-keygen -N "{{ item.0.password }}" -f {{ item.0.path }}
  when: item.1.stat.exists == False
  with_together:
    - ssh_key_files
    - result.results
